### PR TITLE
Added a drawing function

### PR DESCRIPTION
**Pull request by Filco306**
Hey, 

Thank you for a great package! Really happy you made this, as it has helped me get into the area a little bit more. I though I would add a function `draw()` to the base class `SimplicialComplex` using networkx as a tool to draw the Simplicial Complex. This enables the quick drawing of any simplicial complex constructed. 

My basic contributions. 
- Created function `generate_graph()` in the base class `SimplicialComplex` that creates two sets, `vertices` and `edges`.
- Created function `draw()` in the base class `SimplicialComplex` that draws and displays the picture. More options could probably be added here. 
- Added some linting; that is probably why it looks messier than it is.

### CODE REVIEW

**Comment by stephenhky** [comment]
Thanks! Let me review it a bit first!

**Comment by stephenhky** [comment]
Let me remove Python 3.5 dependence. It has been causing me trouble in a lot of other projects.

**Comment by stephenhky** [comment]
I would suggest you merge this PR first: https://github.com/Filco306/MoguTDA/pull/1

**Comment by Filco306** [comment]
Merged it, and it passes :) although I think some unit tests might be appropriate to add, even though I added some for `generate_graph()`. The `draw()` function I am not entirely sure how to create a test for.

**Comment by stephenhky** [comment]
I merged the PR. There is one thing about visualizing the simplex: if the simplex has three points, this way cannot visualize it. But I do not have a solution to that though.

**Comment by Filco306** [comment]
Interesting. I'll have a look and try to see why, and otherwise fix something better! I was also thinking of adding some persistence features, such as barcode generators etc.

**Comment by stephenhky** [comment]
Thanks! That is not a bug, but I saw a lot of books do that.
It would be great if we have persistence too.

**Pull request merged**
